### ISSUE TITLE
Content meta & automation script

### ISSUE THREAD

**Issue by itsjoekent** [itsjoekent/dotnyc#2]
## Metadata
- [x] Define metadata spec. Should include pathname, tags, published timestamp and HTML meta.
- ~Support metadata in the Markdown file. Ensure markdown parser ignores this text.~

## Automation
- [x] Create Node Script to parse all of the markdown files in the `public/content` folder.
- [x] Add all pages to the `src/contentIndex.json` file (Path & tags only, not entire data set)
- ~Place all additional content meta within a json file in the content pages specific directory~
- [x] Run image optimization script

## Image Optimization
The goal of this is to create optimized versions of all images. For now an optimized version is simply a blurred, downscaled photo that can act as a placeholder until the full image is completed downloading in the background later. [Example](https://jmperezperez.com/medium-image-progressive-loading-placeholder/) here.

- ~Create a meta json file w/ all of the image path data~
- ~Add original image dimensions to meta~
- [x] Create a blurry, downscaled version of the image
- ~Create a small 'icon' sized version of the image for use in a Gallery~
- ~Process any image specified in the page meta for proper social dimensions~
- ~If there is a solid NPM package that makes this dead simple, run the image through an optimizer. (_Dead simple means I need 1 function and it doesn't care if its png or jpg_)~

**Comment by itsjoekent** [comment]
Example header spec 

```
[META]
title=Example title
cover=./cover.png
description=Example description
path=/example
[/META]

Normal markdown content goes here
```

Images should be located automatically and processed
